services:
  mongo-db:
    container_name: despliegue-mongo
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testing
      MONGO_INITDB_DATABASE: names
    ports:
      - 27018:27017
    volumes:
      - ./database:/data/db
      - ./scripts-mongo/test.js:/docker-entrypoint-initdb.d/test.js:ro
    networks:
      - network-despliegue

  node:
    container_name: despliegue-node
    build:
      context: .
      dockerfile: Node.Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - mongo-db
    networks:
      - network-despliegue

  nginx:
    container_name: despliegue-nginx
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - node
    networks:
      - network-despliegue

networks:
  network-despliegue: